<a href="https://colab.research.google.com/github/basarrkaya/mlbiokickstart/blob/main/githubTrial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("hello world with başar as a computational biologist")

hello world with başar as a computational biologist

In [ ]:
print("we will do good work here")

we will do good work here

In [ ]:
!git clone https://github.com/basarrkaya/mlbiokickstart
%cd mlbiokickstart

Cloning into 'mlbiokickstart'...
remote: Enumerating objects: 10, done.
remote: Counting objects: 100% (10/10), done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 10 (delta 2), reused 0 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (10/10), done.
Resolving deltas: 100% (2/2), done.
/content/mlbiokickstart/Cancer-Multi-Omics-Benchmark/MLOmics/mlbiokickstart

In [ ]:
!git clone https://github.com/chenzRG/Cancer-Multi-Omics-Benchmark
%cd Cancer-Multi-Omics-Benchmark

Cloning into 'Cancer-Multi-Omics-Benchmark'...
remote: Enumerating objects: 1083, done.
remote: Counting objects: 100% (9/9), done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 1083 (delta 7), reused 3 (delta 3), pack-reused 1074 (from 4)
Receiving objects: 100% (1083/1083), 18.27 MiB | 28.13 MiB/s, done.
Resolving deltas: 100% (231/231), done.
/content/mlbiokickstart/Cancer-Multi-Omics-Benchmark/MLOmics/mlbiokickstart/Cancer-Multi-Omics-Benchmark

In [ ]:
!pip install -r requirements.txt

Requirement already satisfied: numpy>=1.18.2 in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 1)) (2.0.2)
ERROR: Could not find a version that satisfies the requirement tensorflow==2.10.0 (from versions: 2.16.0rc0, 2.16.1, 2.16.2, 2.17.0rc0, 2.17.0rc1, 2.17.0, 2.17.1, 2.18.0rc0, 2.18.0rc1, 2.18.0rc2, 2.18.0, 2.18.1, 2.19.0rc0, 2.19.0, 2.19.1, 2.20.0rc0, 2.20.0, 2.21.0rc0, 2.21.0rc1, 2.21.0)
ERROR: No matching distribution found for tensorflow==2.10.0

In [ ]:
!rm -rf Main_Dataset
!chmod +x ./download.sh
!./download.sh

Cloning into 'MLOmics'...
remote: Enumerating objects: 435, done.
remote: Total 435 (delta 0), reused 0 (delta 0), pack-reused 435 (from 1)
Receiving objects: 100% (435/435), 57.17 KiB | 2.86 MiB/s, done.
Resolving deltas: 100% (56/56), done.
Filtering content: 100% (235/235), 8.83 GiB | 27.51 MiB/s, done.
Main_Dataset Folder has been downloaded and extracted to the current directory.

In [ ]:
import pandas as pd

class_gsbrca_org_methy_df = pd.read_csv('/content/mlbiokickstart/Cancer-Multi-Omics-Benchmark/MLOmics/Main_Dataset/Classification_datasets/GS-BRCA/Original/BRCA_Methy.csv')
class_gsbrca_org_mrna_df = pd.read_csv('/content/mlbiokickstart/Cancer-Multi-Omics-Benchmark/MLOmics/Main_Dataset/Classification_datasets/GS-BRCA/Original/BRCA_mRNA.csv')
class_gsbrca_org_CNV_df = pd.read_csv('/content/mlbiokickstart/Cancer-Multi-Omics-Benchmark/MLOmics/Main_Dataset/Classification_datasets/GS-BRCA/Original/BRCA_CNV.csv')

In [ ]:
class_gsbrca_org_methy_df

,Unnamed: 0,TCGA.3C.AAAU.01,TCGA.3C.AALI.01,TCGA.3C.AALJ.01,TCGA.3C.AALK.01,TCGA.5L.AAT0.01,TCGA.5T.A9QA.01,TCGA.A1.A0SB.01,TCGA.A1.A0SE.01,TCGA.A1.A0SF.01,...,TCGA.UL.AAZ6.01,TCGA.UU.A93S.01,TCGA.V7.A7HQ.01,TCGA.W8.A86G.01,TCGA.WT.AB41.01,TCGA.WT.AB44.01,TCGA.XX.A899.01,TCGA.XX.A89A.01,TCGA.Z7.A8R5.01,TCGA.Z7.A8R6.01
0,A1BG,-1.211396,0.974531,0.633283,0.354642,-1.939963,1.328608,0.946010,0.930281,-0.519615,...,-0.760042,1.159665,0.333349,0.775567,-0.778884,0.517100,0.177384,-0.380611,0.811548,-0.819564
1,A1CF,-1.801239,-1.091976,-0.258825,0.344929,-0.018208,-1.007907,1.246215,0.360814,-0.426866,...,-0.582298,-2.142905,-0.306365,0.816486,-0.499731,0.824666,0.807188,-0.027147,0.644539,-2.004627
2,A2M,-0.696763,-1.597015,-0.873714,-1.080573,-0.788607,-0.583001,-0.654375,0.302439,-1.561816,...,-1.001059,-2.915892,0.635853,0.027964,-1.145160,-0.326970,0.569131,-2.613169,-0.507579,-0.339844
3,A2ML1,0.832338,0.758754,0.753608,0.548382,0.589277,0.870132,-1.878898,0.160075,0.066117,...,0.892903,-2.480427,0.319169,-0.098838,0.830086,0.617726,0.551416,0.101744,0.269641,-0.094397
4,A3GALT2,0.857098,0.450506,0.821330,0.497375,0.400632,1.183863,-3.316770,0.227579,0.051009,...,1.161783,-1.863239,0.350236,-0.879849,-0.098983,0.524779,0.041604,0.537643,-0.322718,0.007108
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19044,ZYG11B,1.079773,1.107008,1.143368,1.327138,0.825476,1.014806,-0.726589,0.116715,-0.967701,...,0.501544,1.248136,-0.609775,0.259632,1.086309,1.867683,0.048509,-0.122038,0.896755,-0.756927
19045,ZYX,0.780058,0.404568,-0.583163,0.047150,0.272223,1.304881,-0.084193,-0.078364,-0.585443,...,0.578764,1.092554,0.706154,-0.837710,1.021682,1.258202,-0.639635,-0.988974,1.156913,-1.043962
19046,ZZEF1,0.747015,0.107306,0.034379,0.014622,0.298979,1.151613,-0.621557,-0.887355,-0.625655,...,0.277770,0.629951,0.062128,-0.269128,0.820279,0.573421,-0.542603,-0.854843,0.898579,-0.878013
19047,ZZZ3,0.378339,0.271888,-0.170242,0.484366,0.029261,0.970602,-0.468274,-0.221699,-0.738370,...,0.781932,0.620894,-0.375671,-0.597399,0.227439,1.354182,-0.548846,-0.365477,-0.098397,-0.763912
19048,pk,0.032275,-0.147645,0.748945,0.173110,-0.424061,2.038508,-0.932571,0.062171,-0.914940,...,0.869040,0.332195,-0.451941,-0.707286,2.407662,0.268539,-0.346807,-0.360622,1.970558,-1.165084

In [ ]:
class_gsbrca_org_CNV_df

,Unnamed: 0,TCGA.3C.AAAU.01,TCGA.3C.AALI.01,TCGA.3C.AALJ.01,TCGA.3C.AALK.01,TCGA.5L.AAT0.01,TCGA.5T.A9QA.01,TCGA.A1.A0SB.01,TCGA.A1.A0SE.01,TCGA.A1.A0SF.01,...,TCGA.UL.AAZ6.01,TCGA.UU.A93S.01,TCGA.V7.A7HQ.01,TCGA.W8.A86G.01,TCGA.WT.AB41.01,TCGA.WT.AB44.01,TCGA.XX.A899.01,TCGA.XX.A89A.01,TCGA.Z7.A8R5.01,TCGA.Z7.A8R6.01
0,A1BG,0.495252,1.028904,0.003059,-0.258705,-0.083232,-0.486242,-0.111192,-0.102997,0.687116,...,-0.493956,2.097171,-0.594226,0.478862,-1.755051,-0.835261,-0.148311,0.557439,-0.234602,-0.838154
1,A1CF,-0.938762,-1.575977,0.405308,0.096910,0.060782,2.050968,0.154506,0.018894,1.131535,...,-0.299975,6.501006,0.255559,-0.184784,0.371274,0.483323,0.061306,0.627836,0.070730,-0.463861
2,A2M,0.750838,0.010864,0.103201,-0.169130,-2.090765,-0.216362,-0.062751,-0.056368,0.857217,...,1.139760,-1.938856,0.036395,-0.308274,0.118520,0.266599,-0.089133,0.344469,0.226601,-0.590817
3,A2ML1,0.748593,0.005894,0.098571,-0.174763,-2.103474,-0.222169,-0.067992,-0.061585,0.855364,...,1.138948,-1.951005,0.031519,-0.314419,0.113946,0.262571,-0.094471,0.340728,0.222425,-0.598003
4,A3GALT2,1.093743,-1.575680,-0.706498,0.199712,0.376570,-2.334753,0.400443,0.225047,1.226264,...,-2.541330,-1.587373,0.371698,0.096424,-1.494803,-2.569588,0.046241,-1.244865,-0.252418,-0.264599
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19563,ZYG11B,1.267331,-1.793233,-0.872324,0.058733,0.242915,-2.475162,0.263210,0.085117,1.176508,...,-0.169592,0.192176,0.237841,-0.048833,-1.672982,-2.900353,-0.073695,-0.277665,-0.435463,-0.424808
19564,ZYX,0.963246,1.446230,0.039191,-0.257130,-0.185487,-1.970238,-0.112381,-0.106533,0.704939,...,-0.542729,-0.489606,-0.134313,0.310169,-0.002235,1.155757,-0.286372,0.253634,-0.327799,-0.589030
19565,ZZEF1,-0.580418,-0.790000,-1.421040,-1.377441,-0.999581,1.646581,0.848410,-0.727278,-0.501251,...,-1.375911,-0.695152,0.920311,-0.919650,-0.690180,0.438043,0.811313,-0.470272,0.723732,-2.171404
19566,ZZZ3,1.715811,-1.268621,-0.811368,0.098802,0.204322,-1.930651,0.307432,0.230822,-1.278740,...,-2.491497,-0.100674,0.289605,-0.009609,-1.555790,-2.902013,-0.051046,-0.247150,-0.350742,-0.339178
19567,pk,-0.864183,0.345052,-1.357237,0.042601,0.078553,-6.994250,0.189832,0.289698,-0.088652,...,-0.314635,-0.081233,0.120782,-0.163409,0.391276,0.247469,-0.178246,-0.427626,0.076841,-0.211344

In [ ]:
class_gsbrca_org_mrna_df

,Unnamed: 0,TCGA.3C.AAAU.01,TCGA.3C.AALI.01,TCGA.3C.AALJ.01,TCGA.3C.AALK.01,TCGA.5L.AAT0.01,TCGA.5T.A9QA.01,TCGA.A1.A0SB.01,TCGA.A1.A0SE.01,TCGA.A1.A0SF.01,...,TCGA.UL.AAZ6.01,TCGA.UU.A93S.01,TCGA.V7.A7HQ.01,TCGA.W8.A86G.01,TCGA.WT.AB41.01,TCGA.WT.AB44.01,TCGA.XX.A899.01,TCGA.XX.A89A.01,TCGA.Z7.A8R5.01,TCGA.Z7.A8R6.01
0,A1BG,1.389927,1.522872,1.788271,-0.288543,-0.462680,-0.451169,-0.805973,-0.472368,0.112737,...,-1.828641,0.756934,1.095019,2.453552,-1.526821,0.108732,-0.219390,-0.112740,-0.920878,0.079873
1,A1BG.AS1,0.436758,1.815091,0.580557,-0.250194,-0.091285,-0.688598,-1.037605,0.658661,0.627872,...,-2.123590,-0.556860,-1.271019,1.915429,-2.519037,-0.643504,0.082909,0.284536,-0.372892,0.539919
2,A2M,-0.876187,-0.508085,-0.258138,-0.030804,0.289970,-1.641876,1.534552,0.436717,0.476992,...,-1.493460,-1.848483,-0.608446,0.584722,-0.267116,-1.271778,0.780906,0.292935,1.883640,-0.469512
3,A2M.AS1,1.607818,0.863019,-0.491954,-0.579638,0.572883,-0.836306,0.099614,-0.059346,-0.092982,...,0.851988,-2.180389,-1.614497,0.398519,-0.632821,-0.768806,0.200613,0.351478,0.015328,-1.309134
4,A2ML1,-0.415138,-0.406608,-0.455969,-0.464938,-0.438571,-0.479607,-0.444955,-0.539629,-0.408042,...,0.419145,-0.483924,-0.379297,-0.406793,-0.470376,-0.429807,-0.491028,0.421906,-0.456669,-0.394471
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18201,ZYG11A,1.753777,1.298863,2.105007,0.916528,-1.152811,-1.553161,-1.086313,-0.380918,0.077010,...,-0.205382,-1.236795,-0.879588,0.043753,-0.663033,-0.044914,-1.729619,0.464810,-0.583245,0.691664
18202,ZYG11B,2.013674,-0.140439,-0.334864,-0.278901,0.075213,-1.397447,1.450555,0.230984,0.050613,...,-1.097367,-0.605515,-2.238730,-0.984880,-2.712107,-2.221944,-0.111461,-0.145830,-0.852285,-0.082546
18203,ZYX,-0.424991,0.635518,0.573943,0.515520,-0.100236,-0.472842,1.176967,-0.169919,0.889745,...,-0.506783,0.348413,0.639343,0.751580,0.809117,1.948080,0.471641,0.436309,0.871434,-0.519024
18204,ZZEF1,1.214399,0.302547,-0.379244,-0.939663,-0.485591,0.190737,1.560267,-0.492343,-0.513877,...,-0.177477,-1.640577,-1.631756,-0.241382,-1.675505,-1.128941,1.749823,0.586414,-1.068255,-1.364660
18205,ZZZ3,1.667340,-1.162286,-0.547104,0.057166,1.268702,-0.622851,0.954347,0.581995,-1.422932,...,-1.500155,-1.441312,-2.351399,0.665626,-1.768910,-1.289816,-0.091739,0.426581,0.430341,-0.720639